<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>GoDesk</RootNamespace>
    <AssemblyName>GoDesk</AssemblyName>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GoConsoleOS.Shared\GoConsoleOS.Shared.csproj" />
  </ItemGroup>
</Project>
